# Objective:
# Learn NumPy for fast numerical computation
# Apply it on bhavcopy data to calculate returns and volatility

In [1]:
import numpy as np
import pandas as pd

In [8]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]

In [ ]:
prices = [100, 102, 101, 105] # it is a list of closing prices for 4 days
np_prices = np.array(prices) # it converts the list of prices into a numpy array

In [11]:
returns = (np_prices[1:] - np_prices[:-1]) / np_prices[:-1]
returns

array([ 0.02      , -0.00980392,  0.03960396])

In [14]:
arr + 10
arr * 2
arr / 2
arr

array([1, 2, 3, 4])

In [15]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr1 + arr2

array([5, 7, 9])

In [ ]:
np.mean(arr)

np.float64(2.5)

In [20]:
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))   # volatility

4
1
1.118033988749895

In [21]:
arr = np.array([10, 20, 30, 40, 50])

arr[0]      # first
arr[-1]     # last
arr[1:4]    # slice

array([20, 30, 40])

In [23]:
arr[arr > 35]

array([40, 50])

In [24]:
arr = np.array([100, 102, 101])

arr - 100

array([0, 2, 1])

In [25]:
prices = np.array([100, 102, 101, 105])

returns = (prices[1:] - prices[:-1]) / prices[:-1]
print(returns)

[ 0.02       -0.00980392  0.03960396]

In [26]:
log_returns = np.log(prices[1:] / prices[:-1])
print(log_returns) # log return is the natural logarithm of the ratio of consecutive prices. It is often used in finance because it has nice properties, such as being time-additive and more normally distributed than simple returns.

[ 0.01980263 -0.0098523   0.03883983]

In [27]:
np.std(returns) # volatility of returns

np.float64(0.020313454228698492)

PROJECT ON NUMPY

In [41]:
df = pd.read_csv("../data/bhavcopy.csv")

df.head()

,SYMBOL,SERIES,DATE1,PREV_CLOSE,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,LAST_PRICE,CLOSE_PRICE,AVG_PRICE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES,DELIV_QTY,DELIV_PER
0,1018GS2026,GS,22-Apr-2026,102.98,102.79,102.99,102.79,102.99,102.99,102.98,349,0.36,11,349,100.00
1,20MICRONS,EQ,22-Apr-2026,177.43,178.14,179.58,177.10,179.24,178.38,178.38,65747,117.28,1374,34726,52.82
2,21STCENMGM,EQ,22-Apr-2026,33.71,34.31,34.38,34.31,34.38,34.38,34.36,4514,1.55,14,4514,100.00
3,360ONE,EQ,22-Apr-2026,1108.35,1114.00,1123.80,1042.00,1055.00,1054.90,1068.54,5903548,63081.65,127390,2433064,41.21
4,3BBLACKBIO,EQ,22-Apr-2026,1388.05,1399.00,1399.00,1341.05,1350.10,1355.15,1368.79,3250,44.49,507,2074,63.82

In [39]:
print(df.columns)

Index(['SYMBOL', 'SERIES', 'DATE1', 'PREV_CLOSE', 'OPEN_PRICE', 'HIGH_PRICE',
       'LOW_PRICE', 'LAST_PRICE', 'CLOSE_PRICE', 'AVG_PRICE', 'TTL_TRD_QNTY',
       'TURNOVER_LACS', 'NO_OF_TRADES', 'DELIV_QTY', 'DELIV_PER', 'NP_RETURN',
       'Returns'],
      dtype='object')

In [45]:
df.columns = df.columns.str.strip() # it removes the leading and trailing spaces from the column names

In [32]:
# extracting closing prices as numpy array
close = df["CLOSE_PRICE"].values

print(type(close))  # should show numpy array

<class 'numpy.ndarray'>

In [48]:
import numpy as np

prices = df['CLOSE_PRICE'].values # it extracts the 'CLOSE_PRICE' column from the DataFrame and converts it into a numpy array. This allows us to perform efficient numerical operations on the closing prices, such as calculating returns, volatility, etc.

returns = (prices[1:] - prices[:-1]) / prices[:-1]

df['Returns'] = np.nan
df.loc[1:, 'Returns'] = returns # it assigns the calculated returns to a new column 'Returns' in the DataFrame. The first row is set to NaN because there is no previous price to calculate the return for the first day.
Returns = df['Returns'].values

In [49]:
Returns

array([        nan,  0.73201282, -0.80726539, ...,  0.11279489,
        2.42252484, -0.45881278], shape=(3234,))

In [60]:
df.head(1)

,SYMBOL,SERIES,DATE1,PREV_CLOSE,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,LAST_PRICE,CLOSE_PRICE,AVG_PRICE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES,DELIV_QTY,DELIV_PER,Returns,Log_Returns,Intraday_Range,Volume_Spike,Turnover_per_Trade
0,1018GS2026,GS,22-Apr-2026,102.98,102.79,102.99,102.79,102.99,102.99,102.98,349,0.36,11,349,100.00,NaN,NaN,0.001946,False,0.032727

In [ ]:
log_returns = np.log(prices[1:] / prices[:-1]) # it calculates the log returns by taking the natural logarithm of the ratio of consecutive prices. This is often used in finance because it has nice properties, such as being time-additive and more normally distributed than simple returns.

df['Log_Returns'] = np.nan
df.loc[1:, 'Log_Returns'] = log_returns
Log_Returns = df['Log_Returns'].values

In [ ]:
df['Intraday_Range'] = (df['HIGH_PRICE'] - df['LOW_PRICE']) / df['LOW_PRICE'] # it calculates the intraday range as the difference between the high and low prices divided by the low price, and stores it in a new column 'Intraday_Range' in the DataFrame. This gives us a measure of the volatility within a single trading day.

In [55]:
avg_volume = np.mean(df['TTL_TRD_QNTY']) # it calculates the average trading quantity (volume) by taking the mean of the 'TTL_TRD_QNTY' column in the DataFrame. This gives us an idea of the typical trading volume for the stocks in our dataset.

df['Volume_Spike'] = df['TTL_TRD_QNTY'] > 2 * avg_volume # it creates a new column 'Volume_Spike' in the DataFrame, which is True if the trading quantity for that row is greater than twice the average volume, and False otherwise. This can help us identify days with unusually high trading activity.

In [ ]:
df['Turnover_per_Trade'] = df['TURNOVER_LACS'] / df['NO_OF_TRADES'] # it calculates the turnover per trade by dividing the total turnover (in lacs) by the number of trades, and stores it in a new column 'Turnover_per_Trade' in the DataFrame. This gives us an idea of the average value of each trade.

In [62]:
df['Bullish_Signal'] = (
    (df['Returns'] > 0) &
    (df['Volume_Spike'])
)

In [64]:
print(np.mean(df['Returns']))
print(np.std(df['Returns']))
print(np.max(df['Returns']))
print(np.min(df['Returns']))

19.3085333151487
162.56229706317512
4612.834355828221
-0.9997348283960907

In [65]:
df.head()
df[['CLOSE_PRICE', 'Returns', 'Log_Returns']].head()

   CLOSE_PRICE    Returns  Log_Returns
0       102.99        NaN          NaN
1       178.38   0.732013     0.549284
2        34.38  -0.807265    -1.646441
3      1054.90  29.683537     3.423726
4      1355.15   0.284624     0.250466