In [28]:
import pandas as pd

df = pd.read_csv("../data/bhavcopy.csv")

df.head()

,SYMBOL,SERIES,DATE1,PREV_CLOSE,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,LAST_PRICE,CLOSE_PRICE,AVG_PRICE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES,DELIV_QTY,DELIV_PER
0,1018GS2026,GS,22-Apr-2026,102.98,102.79,102.99,102.79,102.99,102.99,102.98,349,0.36,11,349,100.00
1,20MICRONS,EQ,22-Apr-2026,177.43,178.14,179.58,177.10,179.24,178.38,178.38,65747,117.28,1374,34726,52.82
2,21STCENMGM,EQ,22-Apr-2026,33.71,34.31,34.38,34.31,34.38,34.38,34.36,4514,1.55,14,4514,100.00
3,360ONE,EQ,22-Apr-2026,1108.35,1114.00,1123.80,1042.00,1055.00,1054.90,1068.54,5903548,63081.65,127390,2433064,41.21
4,3BBLACKBIO,EQ,22-Apr-2026,1388.05,1399.00,1399.00,1341.05,1350.10,1355.15,1368.79,3250,44.49,507,2074,63.82

In [29]:
dimensions = df.shape
print(dimensions)
df.columns # list of column names

df.dtypes

(3234, 15)

SYMBOL             object
 SERIES            object
 DATE1             object
 PREV_CLOSE       float64
 OPEN_PRICE       float64
 HIGH_PRICE       float64
 LOW_PRICE        float64
 LAST_PRICE       float64
 CLOSE_PRICE      float64
 AVG_PRICE        float64
 TTL_TRD_QNTY       int64
 TURNOVER_LACS    float64
 NO_OF_TRADES       int64
 DELIV_QTY         object
 DELIV_PER         object
dtype: object

In [30]:
df.info() # it gives us the number of non-null values in each column and the data type of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3234 entries, 0 to 3233
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SYMBOL          3234 non-null   object
 1    SERIES         3234 non-null   object
 2    DATE1          3234 non-null   object
 3    PREV_CLOSE     3234 non-null   float64
 4    OPEN_PRICE     3234 non-null   float64
 5    HIGH_PRICE     3234 non-null   float64
 6    LOW_PRICE      3234 non-null   float64
 7    LAST_PRICE     3234 non-null   float64
 8    CLOSE_PRICE    3234 non-null   float64
 9    AVG_PRICE      3234 non-null   float64
 10   TTL_TRD_QNTY   3234 non-null   int64
 11   TURNOVER_LACS  3234 non-null   float64
 12   NO_OF_TRADES   3234 non-null   int64
 13   DELIV_QTY      3234 non-null   object
 14   DELIV_PER      3234 non-null   object
dtypes: float64(8), int64(2), object(5)
memory usage: 379.1+ KB

In [31]:
df.describe() # only for numeric columns

,PREV_CLOSE,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,LAST_PRICE,CLOSE_PRICE,AVG_PRICE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES
count,3234.000000,3234.000000,3234.000000,3234.000000,3234.000000,3234.000000,3234.000000,3.234000e+03,3234.000000,3234.000000
mean,919.008949,919.098874,933.498800,908.437100,920.988321,920.800850,920.837081,1.590930e+06,4239.259422,11477.980829
std,4220.756191,4220.592384,4270.622915,4146.256283,4177.315576,4178.457849,4194.900482,1.026595e+07,18266.278289,35418.528944
min,0.270000,0.280000,0.280000,0.270000,0.280000,0.280000,0.280000,1.000000e+00,0.000000,1.000000
25%,55.402500,55.545000,56.435000,54.392500,55.202500,55.147500,55.132500,1.233325e+04,12.215000,110.000000
50%,164.710000,165.545000,169.850000,163.030000,166.550000,166.400000,167.065000,6.944950e+04,113.155000,1043.500000
75%,513.637500,511.250000,526.525000,508.262500,518.787500,518.337500,517.502500,4.395385e+05,1181.155000,7328.750000
max,139665.000000,139600.000000,140095.000000,136165.000000,136890.000000,137040.000000,137737.490000,3.540146e+08,431326.190000,685701.000000

In [32]:
df.isnull().sum() #it tells us how many null values are there in each column

SYMBOL            0
 SERIES           0
 DATE1            0
 PREV_CLOSE       0
 OPEN_PRICE       0
 HIGH_PRICE       0
 LOW_PRICE        0
 LAST_PRICE       0
 CLOSE_PRICE      0
 AVG_PRICE        0
 TTL_TRD_QNTY     0
 TURNOVER_LACS    0
 NO_OF_TRADES     0
 DELIV_QTY        0
 DELIV_PER        0
dtype: int64

In [33]:
df = df.dropna() # it drops all the rows which have at least one null value

In [34]:
# df["CLOSE"] = df["CLOSE"].fillna(df["CLOSE"].mean()) # it fills the null values in the CLOSE column with the mean of the CLOSE column

In [35]:
df.columns = df.columns.str.strip() # it removes the leading and trailing spaces from the column names

In [36]:
df[df["TTL_TRD_QNTY"] > 1000000].head(3) # it gives us all the rows where the total traded quantity is greater than 10 lakhs

,SYMBOL,SERIES,DATE1,PREV_CLOSE,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,LAST_PRICE,CLOSE_PRICE,AVG_PRICE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES,DELIV_QTY,DELIV_PER
3,360ONE,EQ,22-Apr-2026,1108.35,1114.0,1123.8,1042.0,1055.0,1054.9,1068.54,5903548,63081.65,127390,2433064,41.21
61,AARTIIND,EQ,22-Apr-2026,451.20,450.1,472.6,448.5,470.3,470.4,464.89,1546893,7191.36,36086,774090,50.04
67,ABB,EQ,22-Apr-2026,7255.00,7253.0,7822.5,7161.0,7622.0,7587.0,7619.86,1729200,131762.64,150361,453344,26.22

In [37]:
df.sort_values(by="CLOSE_PRICE", ascending=False).head() # it gives us the top 5 rows where the closing price is the highest

,SYMBOL,SERIES,DATE1,PREV_CLOSE,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,LAST_PRICE,CLOSE_PRICE,AVG_PRICE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES,DELIV_QTY,DELIV_PER
1901,MRF,EQ,22-Apr-2026,139665.0,139600.0,140095.00,136165.00,136890.0,137040.0,137737.49,7670,10564.47,6233,3829,49.92
827,ELCIDIN,EQ,22-Apr-2026,128194.9,128250.0,131199.95,125200.05,126153.0,126153.0,127242.76,34,43.26,34,21,61.76
507,BOSCHLTD,EQ,22-Apr-2026,38100.0,38110.0,38395.00,37765.00,37925.0,37885.0,38105.97,26733,10186.87,10269,12607,47.16
2114,PAGEIND,EQ,22-Apr-2026,37960.0,38015.0,38150.00,37750.00,37825.0,37855.0,37895.52,41546,15744.07,9082,31895,76.77
1249,HONAUT,EQ,22-Apr-2026,32620.0,32500.0,32795.00,32205.00,32715.0,32705.0,32506.97,3502,1138.39,2060,1478,42.20

In [38]:
df[df["SERIES"] == "EQ"] # it gives us all the rows where the series is EQ

Empty DataFrame
Columns: [SYMBOL, SERIES, DATE1, PREV_CLOSE, OPEN_PRICE, HIGH_PRICE, LOW_PRICE, LAST_PRICE, CLOSE_PRICE, AVG_PRICE, TTL_TRD_QNTY, TURNOVER_LACS, NO_OF_TRADES, DELIV_QTY, DELIV_PER]
Index: []

In [40]:
df["Range"] = df["HIGH_PRICE"] - df["LOW_PRICE"] # it creates a new column called Range which is the difference between the high and low price of the day

In [42]:
df.head(1)

,SYMBOL,SERIES,DATE1,PREV_CLOSE,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,LAST_PRICE,CLOSE_PRICE,AVG_PRICE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES,DELIV_QTY,DELIV_PER,Range
0,1018GS2026,GS,22-Apr-2026,102.98,102.79,102.99,102.79,102.99,102.99,102.98,349,0.36,11,349,100.00,0.2

In [44]:
df[(df["TTL_TRD_QNTY"] > 1000000) & (df["CLOSE_PRICE"] > 500)].tail()

,SYMBOL,SERIES,DATE1,PREV_CLOSE,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,LAST_PRICE,CLOSE_PRICE,AVG_PRICE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES,DELIV_QTY,DELIV_PER,Range
3083,VEDL,EQ,22-Apr-2026,766.8,769.7,773.85,755.5,758.25,757.00,762.11,14257215,108656.09,179587,6954393,48.78,18.35
3159,WAAREEENER,EQ,22-Apr-2026,3472.8,3472.0,3529.40,3420.8,3427.00,3427.80,3474.05,1301434,45212.48,50938,407298,31.30,108.60
3161,WAAREERTL,EQ,22-Apr-2026,1061.4,1061.5,1122.00,1061.4,1093.50,1093.35,1092.36,1574290,17196.87,57654,311474,19.79,60.60
3172,WELCORP,EQ,22-Apr-2026,1100.6,1112.0,1151.00,1110.0,1148.00,1139.20,1126.64,3972135,44751.55,83799,1937073,48.77,41.00
3221,ZENTEC,EQ,22-Apr-2026,1742.7,1750.0,1788.80,1747.0,1760.20,1762.40,1767.62,1222293,21605.53,59185,335956,27.49,41.80